<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <AssemblyName>RePKG_Re.Application</AssemblyName>
        <RootNamespace>RePKG_Re.Application</RootNamespace>
        <Version>0.4.1</Version>
        <Authors>NotScuffed, ReZe20</Authors>
        <Copyright>Copyright © NotScuffed 2019-2025, ReZe20 2026</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RePKG_Re.Core\RePKG_Re.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
    </ItemGroup>
</Project>
