<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <AssemblyName>RePKG_Re.Core</AssemblyName>
        <RootNamespace>RePKG_Re.Core</RootNamespace>
        <Version>0.5.4</Version>
        <Authors>NotScuffed, ReZe20</Authors>
        <Copyright>Copyright © NotScuffed 2019-2025, ReZe20 2026</Copyright>
    </PropertyGroup>
</Project>
